### Успешный сценарий. Получение ачивок пользователя (200 OK)
GET http://localhost:8083/api/profile/achievements
Accept: application/json
X-Telegram-User-Id: 1201

### Неуспешный сценарий. Отсутствует обязательный загаловок X-Telegram-User-Id (401 Unauthorized)
GET http://localhost:8083/api/profile/achievements
Accept: application/json

### Неуспешный сценарий. Неправильный формат заголовка X-Telegram-User-Id (400 Bad Request)
GET http://localhost:8083/api/profile/achievements
Accept: application/json
X-Telegram-User-Id: not-user

### Неуспешный сценарий. Пользователя не найден (при передаче несуществующего X-Telegram-User-Id) (404 Not found)
GET http://localhost:8083/api/profile/achievements
Accept: application/json
X-Telegram-User-Id: 1234567892131

### Успешный сценарий. Пользователь без ачивок (200 OK)
GET http://localhost:8083/api/profile/achievements
Accept: application/json
X-Telegram-User-Id: 1201