### Успешный сценарий. Получение ачивок пользователя
GET http://localhost:8083/api/achievements
Accept: application/json
X-Telegram-User-Id: 987654321

### Неуспешный сценарий. Отсутствует обязательный загаловок X-Telegram-User-Id:
GET http://localhost:8083/api/achievements
Accept: application/json

### Неуспешный сценарий. Неправильный формат заголовка X-Telegram-User-Id
GET http://localhost:8083/api/achievements
Accept: application/json
X-Telegram-User-Id: not-user

### Неуспешный сценарий. Пользователя не найден
GET http://localhost:8083/api/achievements
Accept: application/json
X-Telegram-User-Id: 1234567892131

### Успешный сценарий. Пользователь без ачивок
GET http://localhost:8083/api/achievements
Accept: application/json
X-Telegram-User-Id: 0785467