### 1. Успешный поиск профиля по ссылке на гитхаб (200 OK)
GET http://localhost:8080/api/profile/internal/profile/by-github-profile-url
    ?url=https://github.com/anelfer



### 2. Поиск профилу по существующей ссылке на телеграмм (404 Not found)
GET http://localhost:8080/api/profile/internal/profile/by-github-profile-url
    ?url=https://t.me/anelfer



### 3. Профиль не найдень (404 Not found)
GET http://localhost:8080/api/profile/internal/profile/by-github-profile-url
    ?url=https://github.com/unknown-github-profile

###