### 1. Успешный поиск профиля по ссылке на гитхаб (200 OK)
GET http://localhost:8083/api/profile/internal/profile/by-github-profile-url
    ?url=https://github.com/anelfer



### 2. Поиск профиля по невалидной ссылке(400 Bad request)
GET http://localhost:8083/api/profile/internal/profile/by-github-profile-url
    ?url=https://invalidUrl.com/test


### 3. Профиль не найден (404 Not found)
GET http://localhost:8083/api/profile/internal/profile/by-github-profile-url
    ?url=https://github.com/unknown-github-profile

###