///200 Успешное обновление профилей пользователя
###
PATCH http://localhost:8083/api/profile
Content-Type: application/json
X-Telegram-User-Id: 39671982

{
  "github_profile_url": "https://github.com/JollykaiTEST1",
  "first_name": "Dmitry",
  "last_name": "OxErr"
}
###

///200 -  Успешное обновление github пользователя
###
PATCH http://localhost:8083/api/profile
Content-Type: application/json
X-Telegram-User-Id: 10001

{
  "github_profile_url": "https://github.com/zhukovaasfssd"
}
###

///400 - No parameters found to update
###
PATCH http://localhost:8083/api/profile
Content-Type: application/json
X-Telegram-User-Id: 10001

{

}
###

///400 -  profile url incorrect
###
PATCH http://localhost:8083/api/profile
Content-Type: application/json
X-Telegram-User-Id: 10001

{
  "github_profile_url": "htt://github.com/zhukovaasfssd",
  "telegram_url": "https://t.me/zhokovsd"
}
###

///403 - попытка изменить "telegram_url"
###
PATCH http://localhost:8083/api/profile
Content-Type: application/json
X-Telegram-User-Id: 39671982

{
  "telegram_url": "https://t.me/zhukovaasfssd"
}
###

///404 - профиль текущего пользователя не существует
###
PATCH http://localhost:8083/api/profile
Content-Type: application/json
X-Telegram-User-Id: 1

{
  "telegram_url": "https://t.me/zhukovaasfssd"
}
###


