server:
  port: 8083

spring:
  application:
    name: profile-service

  datasource:
    url: jdbc:postgresql://localhost:5432/it_mentor_community_platform?currentSchema=profile_service
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092

