spring:
  datasource:
    url: jdbc:postgresql://database:5432/it_mentor_community_platform?currentSchema=profile_service
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092
    topic:
      auth-user-created: auth.user.created
      auth-user-authenticated: auth.user.authenticated
      projects-project-created: projects.project.created

feign:
  client:
    auth-service:
      url: http://auth-service:8080/api/auth