POST http://localhost:8084//api/projects/project
Content-Type: application/json
X-Telegram-User-Id: 1212121212
X-Telegram-Username: telegram_dev_user

{
  "author_telegram_user_id": 1212121212,
  "github_repository_url": "https://github.com/zhukovsd/clou",
  "programming_language": "Java",
  "roadmap_project": "SIMULATION",
  "telegram_user_id": 12144444,
  "added_timestamp:": 123313
}