# Предварительно выполнить -
# INSERT INTO profile_schema.profiles (telegram_user_id) VALUES (1);
# INSERT INTO profile_schema.profiles_details (profile_id, detail_name, detail_value)
# VALUES
#   (1, 'github_profile', 'https://github.com/testuser'),
#   (1, 'telegram_username', '@testuser');


### 1. Успешное получение профиля (Существующий пользователь)
# Предварительно в БД должна быть запись с telegram_user_id = 1
GET http://localhost:8088/api/profile
X-Telegram-User-Id: 1
X-User-Roles: STUDENT

### 2. Ошибка: Профиль не найден (404)
# Пользователь с таким ID (99999) не должен существовать в БД
GET http://localhost:8088/api/profile
X-Telegram-User-Id: 99999
X-User-Roles: STUDENT

### 3. Ошибка: Отсутствует заголовок X-Telegram-User-Id (401/400)
# Проверка обработки отсутствия обязательного заголовка (GlobalExceptionHandler)
GET http://localhost:8088/api/profile
X-User-Roles: STUDENT